### PR TITLE
feat(BE-43): add and improve follow endpoints

### PR DESCRIPTION
**Pull request by Codestronomer**
- add and improve follow endpoint

- add unfollow endpoint

- Add list of followers endpoint

### CODE REVIEW

**Comment by Codestronomer** [comment]
Link to Linear ticket: https://linear.app/team-mallet/issue/BE-43/follow-endpoints

**Comment by timmySpark** [comment]
Has ticket been approved ?

**Comment by Codestronomer** [comment]
Yeah...thanks

**Review by timmySpark — COMMENTED** [review]
Approved for testing , please add merged PR link and docs for testing on Linear

**Pull request merged**
